version: 0.2

phases:
    build:
        commands:
            - echo Building...
            - zip globalclipboard_backend.zip ./Lambda/globalclipboard_backend.py
            - rm ./Lambda/globalclipboard_backend.py
            - cp -R globalclipboard_backend.zip Lambda
            - zip globalclipboard_updater.zip ./Lambda/globalclipboard_updater.py
            - rm ./Lambda/globalclipboard_updater.py
            - cp -R globalclipboard_updater.zip Lambda
            - echo build completed...
artifacts:
    files:
        - Lambda/**/*
        - CloudFormation/**/*